### ISSUE TITLE
Number of images does not match number of timestamps.

### ISSUE THREAD

**Issue by hamitbugrabayram** [AutonomousFieldRoboticsLab/gopro_ros#11]
Hi, 
I faced error about timestamp of images on the video file. I try to run a short video for the test like 20 secs. But when i run the code, this message appears in the terminal then the process die. I did not change anything about video file. 

Also, i'm using gopro 12 black. How can i fix that problem?

**Comment by joshi-bharat** [comment]
I am not so sure. You should upload the file somewhere if you want me to look at it

**Comment by taomiao** [comment]
> Hi, I faced error about timestamp of images on the video file. I try to run a short video for the test like 20 secs. But when i run the code, this message appears in the terminal then the process die. I did not change anything about video file.
> 
> Also, i'm using gopro 12 black. How can i fix that problem?

the same problem occurs.

**Comment by hamitbugrabayram** [comment]
Hi again, 

to solve problem, change the paths in the launch file. The same error sometimes occurs again but it occurs for only ending frames.

**Comment by taomiao** [comment]
> Hi again,
> 
> to solve problem, change the paths in the launch file. The same error sometimes occurs again but it occurs for only ending frames.

change what paths?
