### ISSUE TITLE
This repo's function?

### ISSUE THREAD

**Issue by PengKunPROO** [AutonomousFieldRoboticsLab/gopro_ros#4]
I'm not clearly sure is this repo can use gopro as a webcam to publish image stream to another ros node?

**Comment by joshi-bharat** [comment]
No, this can not use gopro as a webcam. You can use gopro as a webcam, but it is not real time (it is slightly delayed). 

This repo extracts and synchronizes GoPro video and IMU information; so the GoPro can be used as Visual Inertial Sensor. It allows using different SLAM systems as post-processing.
