### ISSUE TITLE
Problem with code gopro_ros

### ISSUE THREAD

**Issue by SnkFst** [AutonomousFieldRoboticsLab/gopro_ros#5]
Hello joshi-bharat,

i'm using your skript and it doesn't work on my machine. I use Ubuntu (Ubuntu 18.04.6 LTS and ros melodic). I followed all your instructions exactly.  I'm trying to get a bag file out of my gopro video.
When i try to run the code from https://github.com/AutonomousFieldRoboticsLab
/
[gopro_ros](https://github.com/AutonomousFieldRoboticsLab/gopro_ros) with an mp4 file from an GoPro08 the 
 prozess shuts down and i get following issue: 

--------------------------------------------------------------------------------------------------------------------------------------------
Progress ..............................................................  [ 99%] [ WARN] [1685523279.887557702]: Number of images does not match number of timestamps. This should only happen in last/single GoPro Video !!
[ WARN] [1685523279.887672736]: Skipping 7/7087 images
Progress ............................................................... [100%]
[ INFO] [1685523279.887891628]: [ACCL] Payloads: 23490
[ INFO] [1685523279.887992233]: [GYRO] Payloads: 23490
================================================================================REQUIRED process [gopro_to_rosbag_DESKTOP_HOAH32N_18999_5900295927244068319-2] has died!
process has finished cleanly
log file: /home/snkfst/.ros/log/1aafbf60-ff90-11ed-9839-00155db56d04/gopro_to_rosbag_DESKTOP_HOAH32N*.log
Initiating shutdown!
================================================================================
[gopro_to_rosbag_DESKTOP_HOAH32N] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
---------------------------------------------------------------------------------------------------------------------------------------------
I tried different videos and another videoformat (AVI), but it didn't help. So im asking you if you know what could lead to the error! 
I'm very gratefull if you could help me! 
Greetings 
SnkFst

**Comment by SnkFst** [comment]
I found the mistake: You have to write the whole path to the video with MP4 and to the output folder, even if you have everything in the gopro_ws

**Comment by joshi-bharat** [comment]
Sure thanks.

**Comment by sajjad-hm** [comment]
@SnkFst Can you please share a sample command line?

**Comment by SnkFst** [comment]
@sajjad-hm  sure

roslaunch gopro_ros gopro_to_rosbag.launch gopro_video:=/home/snkfst/gopro_ws/GH000001.MP4 rosbag:=/home/snkfst/gopro_ws/GH000001.bag

**Comment by sajjad-hm** [comment]
@SnkFst Thank you so much for sharing. Can you please share your GoPro footage properties? i.e. Frame rate & resolution.

**Comment by sajjad-hm** [comment]
@SnkFst @joshi-bharat I'm getting this output. Can you guys please help me on this?

```
roslaunch gopro_ros gopro_to_rosbag.launch gopro_video:=/home/sajjad/gopro_footage/23.mov rosbag:=/home/sajjad/gopro_footage/23.bag
... logging to /home/sajjad/.ros/log/196bff7e-3041-11ee-b57a-e9b7b8c41c67/roslaunch-sajjad-VirtualBox-3726.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://sajjad-VirtualBox:44989/

SUMMARY
========

PARAMETERS
 * /gopro_to_rosbag_sajjad_VirtualBox_3726_5450307341439164251/compressed_image_format: True
 * /gopro_to_rosbag_sajjad_VirtualBox_3726_5450307341439164251/display_images: False
 * /gopro_to_rosbag_sajjad_VirtualBox_3726_5450307341439164251/gopro_folder: /home/bjoshi/gopr...
 * /gopro_to_rosbag_sajjad_VirtualBox_3726_5450307341439164251/gopro_video: /home/sajjad/gopr...
 * /gopro_to_rosbag_sajjad_VirtualBox_3726_5450307341439164251/grayscale: True
 * /gopro_to_rosbag_sajjad_VirtualBox_3726_5450307341439164251/multiple_files: False
 * /gopro_to_rosbag_sajjad_VirtualBox_3726_5450307341439164251/rosbag: /home/sajjad/gopr...
 * /gopro_to_rosbag_sajjad_VirtualBox_3726_5450307341439164251/scale: 0.5
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    gopro_to_rosbag_sajjad_VirtualBox_3726_5450307341439164251 (gopro_ros/gopro_to_rosbag)

auto-starting new master
process[master]: started with pid [3736]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 196bff7e-3041-11ee-b57a-e9b7b8c41c67
process[rosout-1]: started with pid [3746]
started core service [/rosout]
process[gopro_to_rosbag_sajjad_VirtualBox_3726_5450307341439164251-2]: started with pid [3749]
[ INFO] [1690876667.599254550]: [ACCL] Payloads: 0
[ INFO] [1690876667.600604345]: [GYRO] Payloads: 0
================================================================================REQUIRED process [gopro_to_rosbag_sajjad_VirtualBox_3726_5450307341439164251-2] has died!
process has finished cleanly
log file: /home/sajjad/.ros/log/196bff7e-3041-11ee-b57a-e9b7b8c41c67/gopro_to_rosbag_sajjad_VirtualBox_3726_5450307341439164251-2*.log
Initiating shutdown!
================================================================================
[gopro_to_rosbag_sajjad_VirtualBox_3726_5450307341439164251-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by SnkFst** [comment]
@sajjad-hm GoPro Settings: 60fps and resolution 1352 760.

It seems like you video has no ACC und GYRO Data. Try to extract your video as an MP4 file from your gopro.

**Comment by joshi-bharat** [comment]
@sajjad-hm I have not tried with .mov files. Use this tool https://github.com/gopro/gpmf-parser to check if you have IMU payloads. Also, this code works for GoPro 8 and above only.

Another reason, could be you passing wrong path to the file.
