### ISSUE TITLE
Should "Save in Euroc format" reference gopro_to_asl?

### ISSUE THREAD

**Issue by cod3monk3y** [AutonomousFieldRoboticsLab/gopro_ros#6]
In `gopro_ros/README.md`, the section **Save in Euroc format** uses `gopro_to_rosbag.launch` and provides an argument `asl_dir`. However, the file `launch/gopro_to_rosbag.launch` does not have this `asl_dir` param. Should this section of the doc instead use `gopro_to_asl.launch`?

**Comment by joshi-bharat** [comment]
Use gopro_to_asl.launch if you want to save extracted data as raw images and text format.
Use gopto_to_rosbag.launch if you want to save in rosbag.

Both are compatible with EuRoc dataset.

**Comment by cod3monk3y** [comment]
Yes, my point is that the documentation is incorrect.

**Comment by joshi-bharat** [comment]
Euroc format generally means ASL format. 

Rosbag is ROS format.
