### ISSUE TITLE
No visualization from gopro_ros generated bag files

### ISSUE THREAD

**Issue by cod3monk3y** [AutonomousFieldRoboticsLab/gopro_ros#8]
Hi, thanks for this repo by the way. It's certainly saved me some time. 

I'm having an issue where I'm not getting any visualization in RViz from `.bag` files generated from `gopro_ros`. I am able to visualize `MH_01_easy.bag` following the [VINS-Fusion section 3.1 Monocular camera+IMU](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion#31-monocualr-camera--imu). Things I've tried:

1. ensure that the 3 terminals used for `roslaunch`, `rosrun`, and `rosbag play` are all new terminals each time
2. tried 2 different GoPro Hero 9 files (1:08s, and 10m+); they both play back with `rosbag play` but there is no update in RViz  
3. ensured that `MH_01_easy.bag` does play successfully on multiple attempts, and ensured this by doing (1)
4. verified in RViz that the topics show "no data received" for either the image or imu topics when the gopro bag is playing, but do show the number of messages received when playing the `MH_01_easy bag`.
5. noted that the `rosrun vins vins_node` node *does* log data for `MH_01_easy.bag` but *does not* log anything while the gopro `.bag` files are being played
6. verified that `gopro_to_asl` is correctly outputting black and white images, and IMU data at ~200MHz

The only thing I can see so far is that the image topic in the gopro bag is `sensor_msgs/CompressedImage` and in `MH_01_easy.bag` it is `sensor_msgs/Image`. Could that be the issue? Here is the `rosbag info` for both files

### MH_01_easy.bag
```
ubuntu@...:~/catkin_ws/data$ rosbag info MH_01_easy.bag
path:        MH_01_easy.bag
version:     2.0
duration:    3:06s (186s)
start:       Jun 24 2014 19:02:59.81 (1403636579.81)
end:         Jun 24 2014 19:06:06.70 (1403636766.70)
size:        2.5 GB
messages:    47283
compression: none [2456/2456 chunks]
types:       geometry_msgs/PointStamped [c63aecb41bfdfd6b7e1fac37c7cbe7bf]
             sensor_msgs/Image          [060021388200f6f0f447d0fcd9c64743]
             sensor_msgs/Imu            [6a62c6daae103f4ff57a132d6f95cec2]
topics:      /cam0/image_raw    3682 msgs    : sensor_msgs/Image         
             /cam1/image_raw    3682 msgs    : sensor_msgs/Image         
             /imu0             36820 msgs    : sensor_msgs/Imu           
             /leica/position    3099 msgs    : geometry_msgs/PointStamped
```

### GX010421.bag
```
ubuntu@...:~/catkin_ws/data$ rosbag info ./GX010421.bag
path:        ./GX010421.bag
version:     2.0
duration:    1:08s (68s)
start:       Jun 30 2023 12:12:16.13 (1688127136.13)
end:         Jun 30 2023 12:13:24.19 (1688127204.19)
size:        223.9 MB
messages:    15704
compression: none [279/279 chunks]
types:       sensor_msgs/CompressedImage [8f7a12909da2c9d3332d540a0977563f]
             sensor_msgs/Imu             [6a62c6daae103f4ff57a132d6f95cec2]
topics:      /gopro/image_raw/compressed    2040 msgs    : sensor_msgs/CompressedImage
             /gopro/imu                    13664 msgs    : sensor_msgs/Imu
```

Any thoughts on why I'm not getting any visualization from this bag file? Any info I can provide to help diagnose this? 

Thanks.

**Comment by cod3monk3y** [comment]
I regenerated with `compressed_image_format:=false`, so I'm getting `sensor_msgs/Image` now instead of `sensor_msgs/CompressedImage`, but there is no change in behavior.

```
~/catkin_ws/data$ rosbag info GX010421.bag
path:        GX010421.bag
version:     2.0
duration:    1:08s (68s)
start:       Jun 30 2023 12:12:16.13 (1688127136.13)
end:         Jun 30 2023 12:13:24.19 (1688127204.19)
size:        1013.9 MB
messages:    15704
compression: none [1027/1027 chunks]
types:       sensor_msgs/Image [060021388200f6f0f447d0fcd9c64743]
             sensor_msgs/Imu   [6a62c6daae103f4ff57a132d6f95cec2]
topics:      /gopro/image_raw    2040 msgs    : sensor_msgs/Image
             /gopro/imu         13664 msgs    : sensor_msgs/Imu
```

**Comment by cod3monk3y** [comment]
And again, it plays back fine. There's just nothing showing up on the topics.

```
~/catkin_ws/data$ rosbag play ./GX010421.bag      
[ INFO] [1688160032.861143620]: Opening ./GX010421.bag

Waiting 0.2 seconds after advertising topics... done.

Hit space to toggle paused, or 's' to step.
 [RUNNING]  Bag Time: 1688127204.183589   Duration: 68.054675 / 68.064560               
Done.
```

`rosun vins vins_node` just shows "waiting for image and imu..."

```
~$ rosrun vins vins_node ~/catkin_ws/src/VINS-Fusion/config/euroc/euroc_mono_imu_config.yaml 
[ INFO] [1688159980.119619002]: init begins
config_file: /home/ubuntu/catkin_ws/src/VINS-Fusion/config/euroc/euroc_mono_imu_config.yaml
USE_IMU: 1
IMU_TOPIC: /imu0
result path ~/output//vio.csv
[ WARN] [1688159980.123143999]:  fix extrinsic param 
camera number 1
[ INFO] [1688159980.263843502]: Synchronized sensors, fix time offset: 0
[ INFO] [1688159980.263894143]: ROW: 480 COL: 752 
 exitrinsic cam 0
 0.0148655  -0.999881  0.0041403
  0.999557  0.0149672  0.0257155
-0.0257744 0.00375619   0.999661
-0.0216401  -0.064677 0.00981073
set g       0       0 9.81007
[ INFO] [1688159980.264075767]: reading paramerter of camera /home/ubuntu/catkin_ws/src/VINS-Fusion/config/euroc/cam0_mei.yaml
MULTIPLE_THREAD is 1
[ WARN] [1688159980.264303141]: waiting for image and imu..
```

**Comment by cod3monk3y** [comment]
Okay, I understand what's happening. The types are correct but the topics need to be renamed to work with VINS-Fusion:

* `/gopro/image_raw` -> `/cam0/image_raw`
* `/gopro/imu` -> `/imu0`

**Comment by cod3monk3y** [comment]
I got this to work by using `/from_topic:=/to_topic` [remapping syntax](http://wiki.ros.org/Remapping%20Arguments) on the command line. After this, the data shows up as expected in RViz for [VINS-Fusion](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion)

`rosbag play GX010421.bag /gopro/image_raw:=/cam0/image_raw /gopro/imu:=/imu0`

**Comment by cod3monk3y** [comment]
An alternative (and probably the correct) way to do this is to define the topics in your VINS device configuration file. So if you call:

`$ rosrun vins vins_node src/VINS-Fusion/config/gopro/gph9_stdw_config.yaml`

the config should define the topics like so:

```
imu_topic: "/gopro/imu"
image0_topic: "/gopro/image_raw"
```

and then the remapping isn't necessary. 

Closing, as this seems like the correct approach.

**Comment by sajjad-hm** [comment]
@cod3monk3y can you please share how you have created config.yaml file. I'm working with GoPro 8 video file. Can you please share your video recording settings? And which documentation you have followed for calibrating the camera and creating the yaml file? Thanks in advance!
