### ISSUE TITLE
Massive drift, can you review my config?

### ISSUE THREAD

**Issue by cod3monk3y** [AutonomousFieldRoboticsLab/gopro_ros#9]
I see you've gotten the [GPH9 to work with VINS](https://www.youtube.com/watch?v=iNbRslYIQnA). I have ROS, gopro_ros, VINS-Fusion, Kalibr, etc. set up and running, including extraction using `gopro_ros`. However, I'm getting massive amounts of positional drift/acceleration, even when the device is sitting still. Simple movements like tracing the edge of a coffee table or driving a small city block, end up with 10s to 100s of meters off, with the path shooting off in one direction. 

I've fully calibrated my GoPro per [Patrick Geneva's tutorial](https://www.youtube.com/watch?v=rBT5O5TEOV4&t=2789s), and all the bounds in the final report are well within 3 sigma limits. Static, Static IMU, and Dynamic calibration all look very good.

Since you've gotten this working, could you have a look at my config, and let me know if you see anything wrong? And/or do you have your original config posted anywhere? 

GoPro Settings

1. 1080p/24
2. Hypersmoothing is OFF

[cam_gph9_stdw.yaml.txt](https://github.com/AutonomousFieldRoboticsLab/gopro_ros/files/12072457/cam_gph9_stdw.yaml.txt)
[gph9_stdw_config.yaml.txt](https://github.com/AutonomousFieldRoboticsLab/gopro_ros/files/12072458/gph9_stdw_config.yaml.txt)

**Comment by joshi-bharat** [comment]
the parameters look good. I am not sure what's happening with your data.

**Comment by cod3monk3y** [comment]
Okay, thanks for having a look.
